eureka:
  client:
    service-url:
     defaultZone: http://123.207.39.91:8761/eureka/
server:
  port: 8901
spring:
  application:
    name: service-ribbon
  cloud:
    config:
      label: master
      profile: dev
management:
  security:
    enabled: false